### ISSUE TITLE
There is no ready, compiled version?

### ISSUE THREAD

**Issue by adammada** [thatguystone/flowplayer-ima#1]
> Hit the download link and grab the plugin. You can use it just like any other plugin in flowplayer.

Where is it?

**Comment by thatguystone** [comment]
Good catch; I never updated when GitHub deprecated downloadable files.  You can grab it here: https://github.com/thatguystone/flowplayer-ima/blob/master/dist/flowplayer.ima-3.2.7.swf?raw=true
