### ISSUE TITLE
playback control during preroll

### ISSUE THREAD

**Issue by jpriebe** [thatguystone/flowplayer-ima#10]
I'm guessing that I have to explicitly wire the play/pause button to IMA to allow the user to pause during preroll playback.  Is that correct?

Also, I saw mention of "time remaining" displays in other tickets.  Is that something I have to code manually as well?

**Comment by adammada** [comment]
> Also, I saw mention of "time remaining" displays in other tickets. Is that something I have to code manually as well?

Yes, i did that manually.

**Comment by thatguystone** [comment]
Play and pause should work, assuming the FP's standard controls are being used. What're you seeing?

**Comment by thatguystone** [comment]
Closing this since I haven't heard back.
