### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by dennis441970** [thatguystone/flowplayer-ima#16]
I was wondering if your plugin supports Flow Player Flash, and does is also support pre-roll ads? If your plugin does support pre-roll, or mid-roll, what would be an example code mark up for it using your ima plugin? I also want to thank you for creating a plugin like this, because the ova plugin has been discontinued for Flow Player, so you may receive plenty of good responses from your creation.

**Comment by thatguystone** [comment]
This plugin only works with Flowplayer Flash 3.2.*. 

This plugin has full support for flowplayer playlists, so it should be able to handle everything you need. Check out the README for a playlist example.
