### ISSUE TITLE
Google IMA SDK 2 ends September 30 2014

### ISSUE THREAD

**Issue by cbigas** [thatguystone/flowplayer-ima#18]
Can someone please rebuild and post new swf with Google's IMA SDK version 3 please?

**Comment by thatguystone** [comment]
Where are you seeing that support ends 9/30? Also, it's not a simple rebuild; the API from v2 -> v3 changed quite a bit.

@anssip Does the HTML5 player have flash fallback with ads support?

**Comment by anssip** [comment]
Sorry I was actually commenting by accident here :-)

Flowplayer HTML5 does have flash fallback, but the ads are not supported there. Would be great to have a plugin that would use the HTML5 IMA SDK by default and when the player falls back to the "flash engine" it would use the IMA Flash SDK.

**Comment by thatguystone** [comment]
Ah, I wondered where your comment went. You're always welcome to comment here :+1:

**Comment by anssip** [comment]
You should implement a Flowplayer HTML5 compatible plugin!

**Comment by cbigas** [comment]
Our ad agency (google DFP) sent this,

"The old SDK is being deprecated at the end of this quarter (September 30). So, we want to make sure that the small amount of video ads you are serving don't get interrupted. "

**Comment by thatguystone** [comment]
The SDK has been deprecated for a while; do they mean it's being discontinued?

**Comment by cbigas** [comment]
i think that's what they meant. They also provided this link:
https://developers.google.com/interactive-media-ads/docs/sdks/flash/v3/upgrade-v2-to-v3

**Comment by thatguystone** [comment]
I'm checking with Google. That would be really bad.

**Comment by cbigas** [comment]
I was thinking the same thing, and kind of short notice.

**Comment by thatguystone** [comment]
Could you post the full email from them (with your info redacted, if you'd like)?

**Comment by cbigas** [comment]
The short comment was from our DFP ad agency and what I posted was exactly what it said. I will ask for more clarification tomorrow. It may be to meet compliance rather than functionality. Sorry if I caused any unnecessary panic.

**Comment by thatguystone** [comment]
No worries. I'd rather be safe than sorry. Let me know what they say.

**Comment by cbigas** [comment]
Looks like ad-sales did not want to wait until tomorrow. They have verbal confirmation from google that the player will have to be upgraded to IMA3 to be compliant or we will experience an interruption in video ad delivery after next month.

**Comment by thatguystone** [comment]
Yeah, we're getting the same thing from them. I doubt I will have time before Sept 30 to upgrade everything.

Might want to give Flowplayer HTML5 Ads a look: http://demos.flowplayer.org/ads/videoad.html

**Comment by cbigas** [comment]
FYI
So we are not duplicating efforts, I am working on the HTML5 example above but adding companion 250x300 ad call.
