### ISSUE TITLE
Close Ads event

### ISSUE THREAD

**Issue by ghost** [thatguystone/flowplayer-ima#19]
There are events to start( onAdStart ) and finish ( onAdFinish ),

But is there a close event?

or maybe is it possible to call onAdFinish when the user closes the banner?

**Comment by thatguystone** [comment]
Since FP is just a flash object embedded on a page, it doesn't have a built-in "banner", so that would be entirely implementation-specific and up the implementation to fire correctly. If the FP object is destroyed before an ad finishes, I'm not sure if there would even be defined behavior for that.
