### ISSUE TITLE
VAST duration vs FLV duration

### ISSUE THREAD

**Issue by adammada** [thatguystone/flowplayer-ima#3]
Hey, i have VAST link:

http://go.arbopl.bbelements.com/please/showit/416/24/1/43/?detekovano=%2C&keywords=%3B&typkodu=nonstandard

In VAST there is:
[Duration]00:00:20[/Duration]

But FLV has 30 seconds. So Flowplayer runs movie for 20 seconds, then stops. I can click/unlick pause, then it plays rest and then starts to play main clip.

**Comment by thatguystone** [comment]
Good catch on that one.  The older versions of flowplayer never had an issue with the different times (they would look at clip.durationFromMetadata (which was accurate), not clip.duration, but that seems to have changed).  Either way, there's a new binary in the dist/ directory.  Take that one for a spin.

**Comment by adammada** [comment]
Its still broken. Now it plays whole FLV, but next (main) movie starts with "play again" button visible (while playing) and current play time = total time. 
![w1](https://f.cloud.github.com/assets/1177557/403574/aed86d6e-a923-11e2-8578-fe9164e118a6.gif)

Funny, i've set "duration" in playlist config for ima item to 10 seconds, so in player i saw:
- first 10 seconds (because of duration in config)
- then 20 seconds (because of duration from VAST)
- and last 30 seconds (because of FLV length)

Personally i would prefer to stick to the VAST duration if its given (id Ad company makes 30second FLV play 20seconds, lets let them). So "duration" parameter from VAST should work excactly like duration parameter from configuration.

**Comment by thatguystone** [comment]
I don't really think that's a good idea: the video should always be played in full, and I've seen many VAST responses that don't contain a duration, that have an incorrect duration, or had a duration that was too long. As I'm sure we can agree, the intended purpose of an ad is to play all of it, and we should try to do that despite what happens with incorrect VAST.

In my testing, I didn't see the Play Again button come up after the ad, and I'm not sure why Flowplayer would put that there, but I'll poke at it sometime this weekend to see what I can make happen.

**Comment by adammada** [comment]
Here, you can see this bug online:
http://www.sportowefakty.pl/video_test_page

**Comment by adammada** [comment]
I was trying to do something myself, and i've found some workaround. I changed line which you changed last time to:

```
                _clip.duration = o['duration'];
                _clip.durationFromMetadata = o['duration'] + 1;
```

Maybe it has something do do with clip duration being in decimals, like 30.08 in my example.

**Comment by adammada** [comment]
Your solution leads to show lenght of movie in progressbar = 31. For ads its not soo godd, cause they are mostly standarized (10s, 15s, 30s etc). This would work better:

```
            _clip.duration = o['duration'];
            _clip.durationFromMetadata = Math.ceil(o['duration']);
```

**Comment by thatguystone** [comment]
Flowplayer has severe problems with duration. Using your fix, it causes the next clip in the playlist not to play.  For such a tiny problem as being 1 second off, I don't think it's too big of a deal.  Check out Youtube, Hulu, and all those guys: they usually only get within around 3-4 seconds of the actual duration.
