### ISSUE TITLE
Is there other way to play pre-roll than adding it to the playlist?

### ISSUE THREAD

**Issue by adammada** [thatguystone/flowplayer-ima#5]
I'm having problems with flowplayer.

What i want is to play Ad once, then autoplay rest of the playlist, and remove Ad from that playlist.

So i was trying to "edit" playlist in onFinish event of ad - sometimes works, sometimes it just stops working.

Other way was to place Ad as only item on list, then in onFinish event make:

$()f.play( [ urls ] );
console.log( "new_list");

But this also sometimes leads to correct behaviour, but in about half of time it just shows "play again" and doesn't even go to "new_list" line. Some bug in FP? Or i just cant change playlist in clip events?

i ended with:

```
          onFinish: function() { 
              setTimeout(function(){
                $f().play( [ <?= implode( ',', $urls ) ?> ] ); 
              }, 200);  
           } 
```

Because with timeout it seems to work correctly. 

I also had to add timeout to "onAddError" ( Adblock...):

```
        ima: {
            url: "/js/assets/flowplayer/flowplayer.ima-latest.swf",
            onAdError: function() {
                setTimeout(function(){
                    $f().play( [ <?= implode( ',', $urls ) ?> ] ); 
                }, 600);                                        
             }  
        },
```

Questions:
- do you know some way of playing pre-roll once without need to modify playlist?
- or do you know why i'm having those problems when i'm modyfiing playlist to remove ad?

**Comment by thatguystone** [comment]
Afaik, flowplayer doesn't have any internal ways of modifying a playlist during its play, and from my experience, it _hates_ it when you modify _anything_ in an event callback.  The way you have it is probably the best you're going to find.
