### ISSUE TITLE
Blank ad returned

### ISSUE THREAD

**Issue by adammada** [thatguystone/flowplayer-ima#6]
VAST url: http://go.arbopl.bbelements.com/please/showit/416/24/1/43/?detekovano=%2C&keywords=%3B&typkodu=nonstandard

For me its working (Windows 7, on every browser. But my friend has Mac with Chrome (internal flash), and he has problems - no ad played. In debug there is "blank ad returned" error. Main flash movie works, just not ad.

![zzz](https://f.cloud.github.com/assets/1177557/440243/0eaa9d52-b0f9-11e2-9380-f737e5eb1527.jpg)

Any idea?

**Comment by thatguystone** [comment]
I just `curl`ed that URL, and I'm getting nothing in response (aka. a blank ad).  You sure you have the right URL?

**Comment by adammada** [comment]
Interesting. I can open it in browser, but cant wget it. Maybe there is some "anti-hotlink"  feature there, which goes wrong.

Here is this tag used:
http://www.sportowefakty.pl/wideo/iframe/117

**Comment by thatguystone** [comment]
http://go.arbopl.bbelements.com/crossdomain.xml is failing in my browser, so Flash refuses to download anything.  That's probably the problem.

**Comment by adammada** [comment]
I can open it in mine browser. But after you pointed out problem with curl, my friend tried setting different user-agents under safari and it depends on user-agent setting. It doesnt send vast for Safari, but when Safari will say that its Firefox, it will send it. So plugin works perfectly, time to talk with Ad company. Thanks.
