### ISSUE TITLE
"Skippable" ad error

### ISSUE THREAD

**Issue by adammada** [thatguystone/flowplayer-ima#7]
Hi, we are trying to switch to other ad company, but when i'm trying to use their vast its not working:

Here is tag addres:
http://o2.adocean.pl/__/ad.xml?id=CD2VFV5x7Qb7mtpNoChNrBTuwJwtWyL5GQJAY3yN_hv.W7/oacodetype=1/adu=0/emb=1/site=www.sportowefakty.pl/%20key=site_www.sportowefakty.pl%20/%20&_=234

And i got " Error with VAST response: Error #2004 " in console.

**Comment by adammada** [comment]
I edited this xml and found that removing "skip" tracking event makes it work. We even don't support "skipping" of ad, so we even don't need it:

``` xml
<Tracking event="skip"><![CDATA[http://o2adpl.hit.gemius.pl/redot.gif?id=p4CaBrbJt0y1LGlLBhruWqQ_31ku_EbmIujmBCE5SUP.07/stparam=snihfslmho/sarg=52960EF0F97DF684%7C_cdata%3A572756_0%7C_vid%3A542837812665721466%7Csite%3Awww.sportowefakty.pl%7Cowner%3A%7Cfol%3A]]></Tracking>
```

Can you fix it in your plugin?

**Comment by adammada** [comment]
Update: i've compiled your plugin now, and there is difference. Ad works, shows "You can skip this ad in {time}", and after that there is button "skip this ad", but:

a) clikcing in this button skips ad AND opens destination page
b) does not fire correct "onFinish" event.

Now i will just try to make your plugin ignore this parameter.

**Comment by thatguystone** [comment]
The plugin is using Google's IMA SDK v2, which doesn't support VAST3. Since skip is a VAST3 event, I can see it throwing the plugin through a bit of a loop.

What changes did you make to make the plugin show the "You can skip this ad" button?

(Sorry about the delay, it's heavy vacation season.)

**Comment by adammada** [comment]
i just compiled it instead of using ready version. i will try using your most recent build and see.

**Comment by adammada** [comment]
Ok, here is test page, it uses latest swf:

http://sportsboard.pl/stv/

![firefox2](https://f.cloud.github.com/assets/1177557/1731392/c2b9249e-6305-11e3-8c8c-041ad32224e3.png)
![firefox1](https://f.cloud.github.com/assets/1177557/1731395/c4f0cfd2-6305-11e3-964e-f0007d3c1e74.png)
![firefox3](https://f.cloud.github.com/assets/1177557/1731448/795f68d8-6307-11e3-8bc9-ae7df8b5c45e.png)

Most of the time ad loads, but movie isn't scaled properly. But sometimes is.

Anyway - i would like most option to disable it completely.

**Comment by thatguystone** [comment]
Give this a shot: in AdPlayer.as line 342, make it: 

``` actionscript
_currentAd = e['ad'];
_currentAd.skippable = false;
adType = MediaTool.getMediaType(_currentAd['mediaUrl']);
duration = _currentAd['duration'];
_clip.duration = duration;
```

Give that a compile and let's see what happens.

**Comment by adammada** [comment]
Doesn/t compile, gives error:

```
     [exec] AdPlayer.as(343): col: 28 Error: Property is read-only.
     [exec]
     [exec] _currentAd.skippable = false;
```

I was already looking for any solution in docs:
https://developers.google.com/interactive-media-ads/docs/sdks/flash/v2/googleflashas3_apis

and i saw:

https://developers.google.com/interactive-media-ads/docs/sdks/flash/v2/googleflashas3_apis#VideoAdsManager.skipUiContainer

So I thought, that after setting this ui to something invisible it could work, but I haven't managed to do it - I really don't know ActionScript much.

And maybe its that latest ima_lib_as3.swc version, which does that skip ui by itself, which is not what it should do according to docs. Maybe that previous version which gave error when "skip" was set could be make to work by giving invisible skipUiContainer.

**Comment by thatguystone** [comment]
Did you ever get this to work?

**Comment by adammada** [comment]
No.
