### ISSUE TITLE
fresh build

### ISSUE THREAD

**Issue by gkindel** [thatguystone/flowplayer-ima#8]
Looks like the dist has not been rebuilt since the "Crappy VPAID support. Meh." checkin.  Any chance of (or instructions for) a fresh build?

Struggling with VPAID now and hoping to get around this error:
    $f.fireEvent ["onPluginEvent", "ima", "onAdError", 100, "Creative in response not supported", null] 

Much appreciation for the library!

**Comment by adammada** [comment]
You can try that one, i compiled it from most recent source:
http://speedy.sh/RNeZU/flowplayer.ima-3.2.7.swf

**Comment by gkindel** [comment]
Thanks for the response, but I don't think that one is a recent compile.  The speedy.sh file and the one here under /dist/ are both at 32491 bytes and are binary identical according to the the 'diff' shell command.

**Comment by thatguystone** [comment]
Just uploaded a new swf. Let me know if it works.

**Comment by gkindel** [comment]
Works like magic.  Many thanks.  I'll see if I can buy you a tea/coffee for this. =)

**Comment by thatguystone** [comment]
No problem. Thanks for the coffees! :coffee: :tea:
