### ISSUE TITLE
companion issue?

### ISSUE THREAD

**Issue by jpriebe** [thatguystone/flowplayer-ima#9]
First off, thanks for making flowplayer-ima available.  I think we'll be able to make great use of it (and hopefully contribute a thing or two back to the project).

I'm stuck on companion banners.  I'm pretty sure I'm defining my GPT slots properly, and I can see the companion ad details in the VAST response.  But nothing ever gets loaded into the div associated with the slot.

I see that in the CompanionManager.as, you do this:

ExternalInterface.call('writeIntoCompanionDiv', htmlCompanion.content, size);

Am I supposed to define writeIntoCompanionDiv() ?  I tried attaching a function to the global window object, but it never got called.

Any guidance would be much appreciated.

**Comment by jpriebe** [comment]
OK -- maybe I spoke too soon.  I am seeing companions on some of my video ads.  It's possible that my sales team didn't traffic a companion banner for the preroll I was getting earlier.

All that said, what purpose does the writeIntoCompanionDiv call serve?

**Comment by thatguystone** [comment]
The only companions that will be rendered to the page are 300x250 and 300x600, any other sizes are ignored. 

writeIntoCompanionDiv came from Google's sample code for IMA SDK v2, so I just assumed that's valid and still in use, though it's possible that it's bee completely retired in the new version of GPT.
